name: Build Application
on: workflow_dispatch
jobs:
  build-an-application:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64
      - name: Run maven build
        run: mvn clean install
