name: Build, Run, and Push Docker Image

on:
  workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t myfirstapp:latest .

      - name: Run container from built image
        run: |
          docker run --rm myfirstapp:latest

      - name: Tag and push to Docker Hub
        run: |
          docker tag myfirstapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myfirstapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myfirstapp:latest