name: GCR build and push
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Decode base64 key
        id: decode_key
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > sa-key.json
          echo "key_json<<EOF" >> $GITHUB_OUTPUT
          cat sa-key.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ steps.decode_key.outputs.key_json }}'
          export_default_credentials: true

      - name: Docker login to Artifact Registry
        run: |
          docker login -u _json_key --password-stdin https://europe-west3-docker.pkg.dev < sa-key.json

      - name: Build and Push Docker Image
        run: |
          IMAGE="europe-west3-docker.pkg.dev/flawless-augury-461509-f7/demo/app:latest"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
