name: GCR build and push

on:
  workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ AUTHENTICATE WITH GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA }}'   
          export_default_credentials: true

      # ✅ LOG IN TO ARTIFACT REGISTRY
      - name: Docker login to Artifact Registry
        run: |
          echo "${{ secrets.GCP_SA }}" | docker login -u _json_key --password-stdin https://europe-west3-docker.pkg.dev

      # ✅ BUILD AND PUSH IMAGE
      - name: Build and Push Docker image
        run: |
          IMAGE="europe-west3-docker.pkg.dev/flawless-augury-461509-f7/demo/app:latest"
          docker build -t $IMAGE .
          docker push $IMAGE
