
name: GCR build and push

on:
  workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # - name: Build image
      #   run: |
      #     docker build -t myfirstapp:latest .


      # - name: Tag and push to Docker Hub
      #   run: |
      #     docker tag myfirstapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myfirstapp:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/myfirstapp:latest

      - name: Decode and set up GCP credentials
        run: |
          echo "${{ secrets.GCP_SA }}" | base64 --decode > "${HOME}/gcp-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
          gcloud config set project flawless-augury-461509-f7
          gcloud auth configure-docker europe-west3-docker.pkg.dev/ --quiet
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        run: |
          IMAGE="europe-west3-docker.pkg.dev/flawless-augury-461509-f7/demo/app:latest"
          docker build -t $IMAGE .
          docker push $IMAGE
