name: Run Image from Docker Hub

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/demo-java-app:latest

      - name: Run container and wait for app to start
        run: |
          docker run -d --name testapp -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/demo-java-app:latest
          sleep 20  # give app time to start
          docker logs testapp

      - name: Stop and remove container
        if: always()
        run: docker rm -f testapp
