name: Github Context and Expressions
on: workflow_dispatch
jobs:
  use-context-expressions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: list github context with expressions
        run: echo ${{ toJSON(github) }}
